version: '3.8'

services:
  
  bot:
    image: ${BOT_IMAGE}
    restart: always
    environment:
      - URL=${URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SQL_ENGINE_URL=${SQL_ENGINE_URL}
      - LOGGING_CONFIG_PATH=${LOGGING_CONFIG_PATH}
    ports:
      - "8001:80"  

